### PR TITLE
WIP: 2.0.0 Development -> Main

### PR DESCRIPTION
**Pull request by mchalunderscore**
### Changes:
- Internally reworked exit codes to an AppExitCode enum
- Crash, Log and Info macros
- Config format rework
- Added new features:
  - Smart-pull option
  - Build-on-update option
  - Sign on repository generation
  - Reworked prune
- Added new subcommands:
  - A reworked clean, resets the repository to just mlc.toml
  - info, displays repository information as a table
- Lots of internal tweaks and optimisations

## Testers needed !!!

### CODE REVIEW

**Review by axtloss — APPROVED** [review]
Code looks fine to me, but I noticed that you often separated the `!` and the macro name from each other (`log ! (thing)`), I would keep those together (`log!(thing)`), so that it's more visible what is being called.

**Comment by mchalunderscore** [comment]
Strange, this might be an issue with `cargo fmt` as I did not do this myself

**Comment by mchalunderscore** [comment]
New Changes:
- `mlc info` is now a thing, as well as actual config options for workspace mode
- You can now use a second `:` delimiter to specify:
  - Workspace mode: Clone depth (useful for larger repos, e.g. `nixpkgs`
  - Repository mode: Hash to checkout (useful for getting a specific rev of the PKGBUILD)

Re-requesting a bit of testing of edge cases for any potential ugly `unwrap()`s before we can actually merge to `main`

**Review by axtloss — APPROVED** [review]
Basically same thing as last time, code seems fine, but same weird formatting as last time

**Pull request merged**
