### PR TITLE
Changed the way the spinner is stopped

### PR DESCRIPTION
**Pull request by ad4mx**
Hi, author of `spinoff` here. I love your inclusion of my library in this project. I looked at the code, and it seems you are unnecessarily creating a symbol and message variable that you feed into a `stop_and_persist` method when a `success` method would do the same. I also bumped the version number to a newer version that allows printing to `stderr` in case you need to pipe output to something.

### CODE REVIEW

**Comment by mchalunderscore** [comment]
Hi! Thank you for letting us know about this! :)

The main reason we have done as we've done so far is that as it stands right now, just using a success message doesn't fit the formatting for the rest of our info messages. Our info messages use the `colored` library to format the text as bold, and the `success` method doesn't seem to allow for formatting it in such a way (see attached screenshot)

image

Potentially, there could be a way around this (maybe a feature for spinoff that allows the use of `colored`'s `ColoredString` ?)

**Comment by ad4mx** [comment]
I could totally fix the check mark to be bold, I personally also think it's a bit too thin. I can let you know when a new version releases with this change.

**Comment by mchalunderscore** [comment]
That would be awesome! Could there potentially also be an option to make the text bold? As we also do that right now with our current way of formatting. Thanks again of course for reaching out :)

**Comment by ad4mx** [comment]
I'm not so sure, I'm trying to figure out a way right now, but it seems like the only possible solution would be to accept a `ColoredString` instead of a `&'static str`.

**Comment by mchalunderscore** [comment]
As far as I'm aware, borrowing a ColoredString (e.g., `&"Done!".bold()`) parses it as type `&str`, however `success` specifically requires `&'static str`. I've attached a screenshot of the error below:

image

Maybe this is something that could be changed? (e.g., requiring `&str` instead of `&'static str`)

**Comment by ad4mx** [comment]
Seems like changing from `&'static string` to just `&str` is the most sensible option. Like I said, I'll try to get a version with this out of the door as soon as possible.

**Comment by ad4mx** [comment]
Hi @not-my-segfault , version 0.5.2 is released. `sp.success(&"Done!".bold());` should work now.

**Comment by mchalunderscore** [comment]
Thanks for the work, could you potentially change the PR to be pushed to the `malachite/development` branch instead? As we have build releases from our main branch. Thank you!

**Comment by ad4mx** [comment]
Alright, done

**Pull request merged**
